# name: workflow-environments
# on:
#   push:
#     branches:
#       - main
# jobs:
#   stage:
#     permissions:
#       issues: write
#     environment: stage
#     runs-on: ubuntu-latest
#     steps:
#       - name: displaying environment values  
#         run: |
#           echo 'Username: ${{ vars.MONGODB_USERNAME }}'
#           echo 'Password: ${{ secrets.MONGODB_PASSWORD }}'
#           echo 'Database: ${{ vars.MONGODB_DATABASENAME }}'