name: first-workflow
on:
  push:
    branches:
      - 'feature/**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install nodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: building the code
        run: npm run build
      - name: uploading artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  download-artifacts:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: downloading artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: displying artifacts
        run: ls
