name: first-workflow
on:
  push:
    branches:
      - staging
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install nodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: displaying output
        id: publish
        run: echo '::set-output name=username::Vijay'
      - name: cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: run tests
        id: test
        run: npm run test
      - name: execute if previous steps fails
        if: failure() && steps.test.outcome == 'failure'
        run: echo "This step runs when previous step failed."
  deploy:
    if: failure()
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: displaying output from build-and-test
        run: echo 'Something is wrong  '
