name: first-workflow-matrix-strategy
on:
  push:
    branches:
      - main
      - 'feature/**'
      - staging
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [14]
        os: [ubuntu-latest, windows-latest]
        exclude:
          - node-version: 14
            os: [windows-latest, ubuntu-latest]
        include:
          - node-version: 18
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout Code
        uses: actions/checkout@v3
      - name: install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install Dependencies
        run: npm ci
      - name: building the Code
        run: npm run build
