name: first-workflow
on:
  push:
    branches:
      - 'feature/**'
jobs:
  build-and-test:
    outputs:
      username: ${{ steps.publish.outputs.username }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install nodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: displaying output
        id: publish
        run: echo '::set-output name=username::Vijay'
      - name: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: displaying output from build-and-test
        run: echo 'printing output value ${{ needs.build-and-test.outputs.username }} '
