name: first-workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: displaying hello
        run: echo "hello"
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: displaying bye
        run: echo "bye"