name: first-workflow-matrix-strategy
on:
  push:
    branches:
      - main
      - 'feature/**'
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Code
        uses: actions/checkout@v3
      - name: install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: building the Code
        run: npm run build
  deploy:
    needs: build
    uses: ./.github/workflows/second-workflow.yaml
    with:
      name: ${{ github.workflow }}
  testing-output:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: displaying output from another workflow
        run: echo "${{ needs.deploy.outputs.output }}"