name: reusable-workflow
on: 
  workflow_call:
    inputs:
      name:
        description: name of the workflow calling this
        default: default
        required: true
        type: string
    outputs:
      output:
        description: name of the workflow
        value: ${{ steps.result.outputs.result}}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploying
        run: echo "deploying workflow by another workflow - ${{ inputs.name }}"
      - name: output value
        id: result
        run: echo "::set-output name=result::Vijay"